# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UnixTimeConverter
                                 A QGIS plugin
 This basic plugin reformats times stored in unix Timestamp as QGIS-readable datetime
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-12
        copyright            : (C) 2025 by Evan Feusi
        email                : gamfeld@protonmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UnixTimeConverter class from file UnixTimeConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .unix2qgisdatetime import UnixTimeConverter
    return UnixTimeConverter(iface)
